site_name: Modernfit Docs
theme:
  name: material
  palette:
    primary: pink
    accent: cyan
markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.inlinehilite
repo_url: https://github.com/ygModesto/modernfit
repo_name: Modernfit
edit_uri: ""
extra:
  analytics:
    provider: google
    property: UA-176657991-1
